/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StewardshipPhilosophyRouteImport } from './routes/stewardship-philosophy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppTitheRouteImport } from './routes/_app/tithe'
import { Route as AppSubscriptionsRouteImport } from './routes/_app/subscriptions'
import { Route as AppStewardshipRouteImport } from './routes/_app/stewardship'
import { Route as AppStatementsRouteImport } from './routes/_app/statements'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppInvestmentsRouteImport } from './routes/_app/investments'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppIncomeEntriesRouteImport } from './routes/_app/income-entries'
import { Route as AppIncomeRouteImport } from './routes/_app/income'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppGoalsRouteImport } from './routes/_app/goals'
import { Route as AppGivingRouteImport } from './routes/_app/giving'
import { Route as AppFamilyChildRouteImport } from './routes/_app/family-child'
import { Route as AppFamilyRouteImport } from './routes/_app/family'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppDebtsRouteImport } from './routes/_app/debts'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppBudgetsRouteImport } from './routes/_app/budgets'
import { Route as AppAdvisorRouteImport } from './routes/_app/advisor'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'

const StewardshipPhilosophyRoute = StewardshipPhilosophyRouteImport.update({
  id: '/stewardship-philosophy',
  path: '/stewardship-philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppTitheRoute = AppTitheRouteImport.update({
  id: '/tithe',
  path: '/tithe',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppStewardshipRoute = AppStewardshipRouteImport.update({
  id: '/stewardship',
  path: '/stewardship',
  getParentRoute: () => AppRoute,
} as any)
const AppStatementsRoute = AppStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestmentsRoute = AppInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeEntriesRoute = AppIncomeEntriesRouteImport.update({
  id: '/income-entries',
  path: '/income-entries',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeRoute = AppIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppGivingRoute = AppGivingRouteImport.update({
  id: '/giving',
  path: '/giving',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyChildRoute = AppFamilyChildRouteImport.update({
  id: '/family-child',
  path: '/family-child',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyRoute = AppFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtsRoute = AppDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsRoute = AppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvisorRoute = AppAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/stewardship-philosophy': typeof StewardshipPhilosophyRoute
  '/accounts': typeof AppAccountsRoute
  '/advisor': typeof AppAdvisorRoute
  '/budgets': typeof AppBudgetsRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/debts': typeof AppDebtsRoute
  '/expenses': typeof AppExpensesRoute
  '/family': typeof AppFamilyRoute
  '/family-child': typeof AppFamilyChildRoute
  '/giving': typeof AppGivingRoute
  '/goals': typeof AppGoalsRoute
  '/history': typeof AppHistoryRoute
  '/income': typeof AppIncomeRoute
  '/income-entries': typeof AppIncomeEntriesRoute
  '/insights': typeof AppInsightsRoute
  '/investments': typeof AppInvestmentsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/statements': typeof AppStatementsRoute
  '/stewardship': typeof AppStewardshipRoute
  '/subscriptions': typeof AppSubscriptionsRoute
  '/tithe': typeof AppTitheRoute
  '/transactions': typeof AppTransactionsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/stewardship-philosophy': typeof StewardshipPhilosophyRoute
  '/accounts': typeof AppAccountsRoute
  '/advisor': typeof AppAdvisorRoute
  '/budgets': typeof AppBudgetsRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/debts': typeof AppDebtsRoute
  '/expenses': typeof AppExpensesRoute
  '/family': typeof AppFamilyRoute
  '/family-child': typeof AppFamilyChildRoute
  '/giving': typeof AppGivingRoute
  '/goals': typeof AppGoalsRoute
  '/history': typeof AppHistoryRoute
  '/income': typeof AppIncomeRoute
  '/income-entries': typeof AppIncomeEntriesRoute
  '/insights': typeof AppInsightsRoute
  '/investments': typeof AppInvestmentsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/statements': typeof AppStatementsRoute
  '/stewardship': typeof AppStewardshipRoute
  '/subscriptions': typeof AppSubscriptionsRoute
  '/tithe': typeof AppTitheRoute
  '/transactions': typeof AppTransactionsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/stewardship-philosophy': typeof StewardshipPhilosophyRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/advisor': typeof AppAdvisorRoute
  '/_app/budgets': typeof AppBudgetsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/debts': typeof AppDebtsRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/family': typeof AppFamilyRoute
  '/_app/family-child': typeof AppFamilyChildRoute
  '/_app/giving': typeof AppGivingRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/income': typeof AppIncomeRoute
  '/_app/income-entries': typeof AppIncomeEntriesRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/investments': typeof AppInvestmentsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/statements': typeof AppStatementsRoute
  '/_app/stewardship': typeof AppStewardshipRoute
  '/_app/subscriptions': typeof AppSubscriptionsRoute
  '/_app/tithe': typeof AppTitheRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/stewardship-philosophy'
    | '/accounts'
    | '/advisor'
    | '/budgets'
    | '/calendar'
    | '/dashboard'
    | '/debts'
    | '/expenses'
    | '/family'
    | '/family-child'
    | '/giving'
    | '/goals'
    | '/history'
    | '/income'
    | '/income-entries'
    | '/insights'
    | '/investments'
    | '/reports'
    | '/settings'
    | '/statements'
    | '/stewardship'
    | '/subscriptions'
    | '/tithe'
    | '/transactions'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/stewardship-philosophy'
    | '/accounts'
    | '/advisor'
    | '/budgets'
    | '/calendar'
    | '/dashboard'
    | '/debts'
    | '/expenses'
    | '/family'
    | '/family-child'
    | '/giving'
    | '/goals'
    | '/history'
    | '/income'
    | '/income-entries'
    | '/insights'
    | '/investments'
    | '/reports'
    | '/settings'
    | '/statements'
    | '/stewardship'
    | '/subscriptions'
    | '/tithe'
    | '/transactions'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/stewardship-philosophy'
    | '/_app/accounts'
    | '/_app/advisor'
    | '/_app/budgets'
    | '/_app/calendar'
    | '/_app/dashboard'
    | '/_app/debts'
    | '/_app/expenses'
    | '/_app/family'
    | '/_app/family-child'
    | '/_app/giving'
    | '/_app/goals'
    | '/_app/history'
    | '/_app/income'
    | '/_app/income-entries'
    | '/_app/insights'
    | '/_app/investments'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/statements'
    | '/_app/stewardship'
    | '/_app/subscriptions'
    | '/_app/tithe'
    | '/_app/transactions'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  StewardshipPhilosophyRoute: typeof StewardshipPhilosophyRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stewardship-philosophy': {
      id: '/stewardship-philosophy'
      path: '/stewardship-philosophy'
      fullPath: '/stewardship-philosophy'
      preLoaderRoute: typeof StewardshipPhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tithe': {
      id: '/_app/tithe'
      path: '/tithe'
      fullPath: '/tithe'
      preLoaderRoute: typeof AppTitheRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscriptions': {
      id: '/_app/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stewardship': {
      id: '/_app/stewardship'
      path: '/stewardship'
      fullPath: '/stewardship'
      preLoaderRoute: typeof AppStewardshipRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statements': {
      id: '/_app/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof AppStatementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investments': {
      id: '/_app/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AppInvestmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/income-entries': {
      id: '/_app/income-entries'
      path: '/income-entries'
      fullPath: '/income-entries'
      preLoaderRoute: typeof AppIncomeEntriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/income': {
      id: '/_app/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AppIncomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/giving': {
      id: '/_app/giving'
      path: '/giving'
      fullPath: '/giving'
      preLoaderRoute: typeof AppGivingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/family-child': {
      id: '/_app/family-child'
      path: '/family-child'
      fullPath: '/family-child'
      preLoaderRoute: typeof AppFamilyChildRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/family': {
      id: '/_app/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof AppFamilyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/debts': {
      id: '/_app/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof AppDebtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets': {
      id: '/_app/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AppBudgetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/advisor': {
      id: '/_app/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AppAdvisorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppAdvisorRoute: typeof AppAdvisorRoute
  AppBudgetsRoute: typeof AppBudgetsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDebtsRoute: typeof AppDebtsRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppFamilyRoute: typeof AppFamilyRoute
  AppFamilyChildRoute: typeof AppFamilyChildRoute
  AppGivingRoute: typeof AppGivingRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppIncomeRoute: typeof AppIncomeRoute
  AppIncomeEntriesRoute: typeof AppIncomeEntriesRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppInvestmentsRoute: typeof AppInvestmentsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatementsRoute: typeof AppStatementsRoute
  AppStewardshipRoute: typeof AppStewardshipRoute
  AppSubscriptionsRoute: typeof AppSubscriptionsRoute
  AppTitheRoute: typeof AppTitheRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppAdvisorRoute: AppAdvisorRoute,
  AppBudgetsRoute: AppBudgetsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDebtsRoute: AppDebtsRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppFamilyRoute: AppFamilyRoute,
  AppFamilyChildRoute: AppFamilyChildRoute,
  AppGivingRoute: AppGivingRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppIncomeRoute: AppIncomeRoute,
  AppIncomeEntriesRoute: AppIncomeEntriesRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppInvestmentsRoute: AppInvestmentsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatementsRoute: AppStatementsRoute,
  AppStewardshipRoute: AppStewardshipRoute,
  AppSubscriptionsRoute: AppSubscriptionsRoute,
  AppTitheRoute: AppTitheRoute,
  AppTransactionsRoute: AppTransactionsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StewardshipPhilosophyRoute: StewardshipPhilosophyRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
