/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSubscriptionsRouteImport } from './routes/_app/subscriptions'
import { Route as AppStewardshipRouteImport } from './routes/_app/stewardship'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSalaryRouteImport } from './routes/_app/salary'
import { Route as AppInvestmentsRouteImport } from './routes/_app/investments'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppIncomeRouteImport } from './routes/_app/income'
import { Route as AppGoalsRouteImport } from './routes/_app/goals'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppDebtsRouteImport } from './routes/_app/debts'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBudgetsRouteImport } from './routes/_app/budgets'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppStewardshipRoute = AppStewardshipRouteImport.update({
  id: '/stewardship',
  path: '/stewardship',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalaryRoute = AppSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestmentsRoute = AppInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeRoute = AppIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtsRoute = AppDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsRoute = AppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/accounts': typeof AppAccountsRoute
  '/budgets': typeof AppBudgetsRoute
  '/dashboard': typeof AppDashboardRoute
  '/debts': typeof AppDebtsRoute
  '/expenses': typeof AppExpensesRoute
  '/goals': typeof AppGoalsRoute
  '/income': typeof AppIncomeRoute
  '/insights': typeof AppInsightsRoute
  '/investments': typeof AppInvestmentsRoute
  '/salary': typeof AppSalaryRoute
  '/settings': typeof AppSettingsRoute
  '/stewardship': typeof AppStewardshipRoute
  '/subscriptions': typeof AppSubscriptionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/accounts': typeof AppAccountsRoute
  '/budgets': typeof AppBudgetsRoute
  '/dashboard': typeof AppDashboardRoute
  '/debts': typeof AppDebtsRoute
  '/expenses': typeof AppExpensesRoute
  '/goals': typeof AppGoalsRoute
  '/income': typeof AppIncomeRoute
  '/insights': typeof AppInsightsRoute
  '/investments': typeof AppInvestmentsRoute
  '/salary': typeof AppSalaryRoute
  '/settings': typeof AppSettingsRoute
  '/stewardship': typeof AppStewardshipRoute
  '/subscriptions': typeof AppSubscriptionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/budgets': typeof AppBudgetsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/debts': typeof AppDebtsRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/income': typeof AppIncomeRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/investments': typeof AppInvestmentsRoute
  '/_app/salary': typeof AppSalaryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stewardship': typeof AppStewardshipRoute
  '/_app/subscriptions': typeof AppSubscriptionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/accounts'
    | '/budgets'
    | '/dashboard'
    | '/debts'
    | '/expenses'
    | '/goals'
    | '/income'
    | '/insights'
    | '/investments'
    | '/salary'
    | '/settings'
    | '/stewardship'
    | '/subscriptions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/accounts'
    | '/budgets'
    | '/dashboard'
    | '/debts'
    | '/expenses'
    | '/goals'
    | '/income'
    | '/insights'
    | '/investments'
    | '/salary'
    | '/settings'
    | '/stewardship'
    | '/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/accounts'
    | '/_app/budgets'
    | '/_app/dashboard'
    | '/_app/debts'
    | '/_app/expenses'
    | '/_app/goals'
    | '/_app/income'
    | '/_app/insights'
    | '/_app/investments'
    | '/_app/salary'
    | '/_app/settings'
    | '/_app/stewardship'
    | '/_app/subscriptions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/subscriptions': {
      id: '/_app/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stewardship': {
      id: '/_app/stewardship'
      path: '/stewardship'
      fullPath: '/stewardship'
      preLoaderRoute: typeof AppStewardshipRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/salary': {
      id: '/_app/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof AppSalaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investments': {
      id: '/_app/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AppInvestmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/income': {
      id: '/_app/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AppIncomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/debts': {
      id: '/_app/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof AppDebtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets': {
      id: '/_app/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AppBudgetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppBudgetsRoute: typeof AppBudgetsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDebtsRoute: typeof AppDebtsRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppIncomeRoute: typeof AppIncomeRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppInvestmentsRoute: typeof AppInvestmentsRoute
  AppSalaryRoute: typeof AppSalaryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStewardshipRoute: typeof AppStewardshipRoute
  AppSubscriptionsRoute: typeof AppSubscriptionsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppBudgetsRoute: AppBudgetsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDebtsRoute: AppDebtsRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppIncomeRoute: AppIncomeRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppInvestmentsRoute: AppInvestmentsRoute,
  AppSalaryRoute: AppSalaryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStewardshipRoute: AppStewardshipRoute,
  AppSubscriptionsRoute: AppSubscriptionsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
